
# josephjacobson.github.io

The contents here is currently generated by the
[Pelican](https://github.com/getpelican/pelican) static site generator.

See the [pelican](https://github.com/josephjacobson/josephjacobson.github.io/tree/pelican) branch to view the content source.


